package com.srinjay.secureApp.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.security.web.csrf.CsrfToken;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import com.srinjay.secureApp.model.Student;

import jakarta.servlet.http.HttpServletRequest;

@RestController
public class StudentController {
	private List<Student> students = new ArrayList<>(
	        List.of(
	            new Student(1, "Srinjay", 30),
	            new Student(2, "Moumita", 40)
	        )
	    );
	
	@GetMapping("/students")
	public List<Student> getStudents(){
		return students;
	}
	
	@GetMapping("/csrf")
	public CsrfToken getCSRFToken(HttpServletRequest request) {
		return (CsrfToken) request.getAttribute("_csrf");
	}
	
	// Even if we have this mapping, but if we try hitting this url using Postman, we will be getting 401 Error, that is UnAuthorized Error, so to handle this we will need to pass the CSRF Token so that it can validate the token to allow the authorization
	// CSRF token is needed for any POST or PUT or DELETE request. A CSRF token is a unique, random, and secret value generated by a server and included in web application forms or requests to prevent Cross-Site Request Forgery (CSRF) attacks
	@PostMapping("/students")
	public Student addStudent(@RequestBody Student s) {
		students.add(s);
		return s;
	}
			
}
